name: Build VyOS Rolling ISO (NoCloud cloud-init)

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: |
          docker pull vyos/vyos-build:current

      - name: Clone repository and build
        run: |
          git clone -b current --single-branch https://github.com/vyos/vyos-build
          cd vyos-build
          docker run --rm --privileged \
            -v $(pwd):/vyos \
            -w /vyos \
            vyos/vyos-build:current \
            sudo ./build-vyos-image --architecture amd64 --build-by "j.randomhacker@vyos.io" --custom-package cloud-init generic

      - name: List artifacts
        run: ls -lh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: live-image-amd64.hybrid.iso
          path: ./vyos-build/build/*.iso

